export default {
  error: {
    generic: "Error: {{details}}",
    invalidServerUrl: "Invalid Server URL",
    invalidCredentials: "Invalid Email or Password",
  },
  loginRequired: "Login required",
  loginSuccessful: "Login successful!",
  logout: "Logout",
  logoutConfirmMessage: "Are you sure you want to logout?",
  logoutOptions: {
    keepEmailAddress: "Keep email address",
  },
  twoFactorCode: "2FA Code",
  twoFactorRequiredConfirm: {
    title: "2FA Required",
    message: "Please enter the code generated by your authenticator app.",
    messageError: "2FA code is incorrect. Please try again.",
  },
};
