export default {
  about: "About",
  appTitle: "Arena Mobile 2",
  cancel: "Cancel",
  clear: "Clear",
  close: "Close",
  confirm: "Confirm",
  confirmClearSelectedValue: "Clear selected value?",
  confirmClearSelectedValue_plural: "Clear selected values?",
  continue: "Continue",
  createdOn: "Created on",
  delete: "Delete",
  deleteSelectedTitle: "Delete selected",
  details: "Details",
  done: "Done",
  empty: "--- EMPTY ---",
  error: "Error",
  error_other: "Errors",
  exit: "Exit",
  export: "Export",
  false: "False",
  filter: "Filter",
  fromToOf: `{{from}}-{{to}} of {{of}}`,
  goBack: "Go back",
  import: "Import",
  info: "Info",
  label: "Label",
  legend: "Legend",
  modifiedOn: "Modified on",
  name: "Name",
  networkNotAvailable: "Network not available!",
  newItemWithParam: "New {{item}}",
  no: "No",
  noItemsMatchingSearch: "There is no item matching your search",
  notEnoughDiskSpace:
    "Not enough free disk space ({{requiredSpace}} more is required)",
  ok: "Ok",
  path: "Path",
  rowsPerPage: "Rows per page",
  search: "Search",
  selectAnItem: "Select an item",
  selectNewItems: "Select new items",
  shareFile: "Share file",
  size: "Size",
  sizeAvailable: "{{size}} available",
  somethingWentWrong: "Something went wrong: {{error}}",
  srs: "SRS",
  status: "Status",
  stop: "Stop",
  swipeToConfirm: "Swipe to confirm",
  textCopiedToClipboard: "Text copied to clipboard",
  true: "True",
  yes: "Yes",

  timePart: {
    year: "year",
    year_plural: "years",
    month: "month",
    month_plural: "months",
    day: "day",
    day_plural: "days",
    hour: "hour",
    hours: "hours",
    minute: "minute",
    minute_plural: "minutes",
    second: "second",
    second_plural: "seconds",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "It can last around {{hours}} h and {{minutes}} min",
    canLastTimePart: "It can last around {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h and {{minutes}} min",
    lessThanOneTimePart: "less than one {{timePart}} left",
    timePartLeft: "{{count}} {{timePart}} left",
  },
  warning: "Warning",
  warning_other: "Warnings",
};
