export default {
  clearCredentials: "Clear credentials",
  clearCredentialsConfirmMessage: "Clear user credentials?",
  email: "Email",
  errorConnectingWithServer: "Error connecting with server",
  forgotPassword: "Forgot password?",
  login: "Login",
  loginUsingQrCode: "Login using QR code",
  logout: "Logout",
  logoutConfirmMessage: "Logout and clear user credentials?",
  password: "Password",
  qrCodeNotValid: "QR code not valid",
  requestAccess: "New to Arena? Request access",
  scanQrCode: "Scan QR code",
  serverUrl: "Server URL",
  serverUrlNotValid: "Server URL not valid",
  serverUrlType: {
    default: "Default",
    custom: "Custom",
  },
  testUrl: "Test URL",
  title: "Connection to server",
};
