export default {
  about: "Über",
  cancel: "Abbrechen",
  clear: "Leeren",
  close: "Schließen",
  confirm: "Bestätigen",
  confirmClearSelectedValue: "Ausgewählten Wert löschen?",
  confirmClearSelectedValue_plural: "Ausgewählte Werte löschen?",
  continue: "Weiter",
  createdOn: "Erstellt am",
  delete: "Löschen",
  deleteSelectedTitle: "Ausgewählte löschen",
  details: "Details",
  done: "Fertig",
  empty: "--- LEER ---",
  error: "Fehler",
  exit: "Beenden",
  export: "Exportieren",
  false: "Falsch",
  filter: "Filtern",
  fromToOf: `{{from}}-{{to}} von {{of}}`,
  goBack: "Zurück",
  import: "Importieren",
  info: "Info",
  label: "Bezeichnung",
  legend: "Legende",
  modifiedOn: "Geändert am",
  name: "Name",
  networkNotAvailable: "Netzwerk nicht verfügbar!",
  newItemWithParam: "Neu {{item}}",
  no: "Nein",
  noItemsMatchingSearch: "Keine Einträge gefunden, die Ihrer Suche entsprechen",
  notEnoughDiskSpace:
    "Nicht genügend freier Speicherplatz ({{requiredSpace}} mehr erforderlich)",
  ok: "Ok",
  path: "Pfad",
  rowsPerPage: "Zeilen pro Seite",
  search: "Suchen",
  selectAnItem: "Element auswählen",
  selectNewItems: "Neue Elemente auswählen",
  shareFile: "Datei teilen",
  size: "Größe",
  sizeAvailable: "{{size}} verfügbar",
  somethingWentWrong: "Etwas ist schief gelaufen: {{error}}",
  srs: "SRS",
  status: "Status",
  stop: "Stopp",
  swipeToConfirm: "Zum Bestätigen wischen",
  textCopiedToClipboard: "Text in die Zwischenablage kopiert",
  true: "Wahr",
  yes: "Ja",

  timePart: {
    year: "Jahr",
    year_plural: "Jahre",
    month: "Monat",
    month_plural: "Monate",
    day: "Tag",
    day_plural: "Tage",
    hour: "Stunde",
    hours: "Stunden",
    minute: "Minute",
    minute_plural: "Minuten",
    second: "Sekunde",
    second_plural: "Sekunden",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "Es kann ungefähr {{hours}} Stunden und {{minutes}} Minuten dauern",
    canLastTimePart: "Es kann ungefähr {{count}} {{timePart}} dauern",
    hoursAndMinutesShort: "{{hours}} Std. und {{minutes}} Min.",
    lessThanOneTimePart: "weniger als eine {{timePart}} übrig",
    timePartLeft: "{{count}} {{timePart}} übrig",
  },
  tryAgain: "Erneut versuchen",
  warning: "Warnung",
};
