sonar.projectKey=openforis_arena-mobile
sonar.organization=openforis

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=arena-mobile
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# TESTs
sonar.tests=src
# But we get specific here
# We don't need to exclude it in sonar.sources because it is automatically taken care of
sonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx


sonar.coverage.exclusions=**/android/**/*.*,**/ios/**/*.* 
sonar.exclusions=**/android/**/*.*,**/ios/**/*.*
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml

sonar.sourceEncoding=UTF-8

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx


# disabled rules
sonar.issue.ignore.multicriteria=S3317

sonar.issue.ignore.multicriteria.S3317.ruleKey=javascript:S3317
sonar.issue.ignore.multicriteria.S3317.resourceKey= **/*


