sonar.projectKey=openforis_arena-mobile
sonar.organization=openforis

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=arena-mobile
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8


sonar.coverage.exclusions=**/android/**/*.*,**/ios/**/*.* 
sonar.exclusions=**/android/**/*.*,**/ios/**/*.*

sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx


# disabled rules
sonar.issue.ignore.multicriteria=e1

sonar.issue.ignore.multicriteria.e1.ruleKey=java:javascript:S3317
sonar.issue.ignore.multicriteria.e1.resourceKey=**/screen.js, **/actionCreators.js,  **/reducers.js, **/store.js, **/sagas.js