export default {
  about: "このアプリについて",
  appTitle: "Arena Mobile",
  cancel: "キャンセル",
  clear: "クリア",
  close: "閉じる",
  confirm: "確認",
  confirmClearSelectedValue: "選択した値をクリアしますか？",
  confirmClearSelectedValue_plural: "選択した値をクリアしますか？",
  continue: "続ける",
  createdOn: "作成日",
  delete: "削除",
  deleteSelectedTitle: "選択項目を削除",
  details: "詳細",
  done: "完了",
  empty: "--- 空 ---",
  error: "エラー",
  error_other: "エラー",
  exit: "終了",
  export: "エクスポート",
  false: "誤",
  filter: "フィルター",
  fromToOf: `{{from}}-{{to}} / {{of}}`,
  goBack: "戻る",
  import: "インポート",
  info: "情報",
  label: "ラベル",
  legend: "凡例",
  modifiedOn: "更新日",
  name: "名前",
  networkNotAvailable: "ネットワークが利用できません！",
  newItemWithParam: "新規{{item}}",
  no: "いいえ",
  noItemsMatchingSearch: "検索に一致する項目がありません",
  notEnoughDiskSpace:
    "ディスクの空き容量が不足しています（さらに{{requiredSpace}}必要です）",
  ok: "OK",
  openSettings: "設定を開く",
  path: "ファイルパス",
  rowsPerPage: "1ページあたりの行数",
  search: "検索",
  selectAnItem: "項目を選択",
  selectNewItems: "新しい項目を選択",
  shareFile: "ファイルを共有",
  size: "サイズ",
  sizeAvailable: "{{size}} 利用可能",
  somethingWentWrong: "問題が発生しました：{{error}}",
  srs: "SRS",
  status: "状態",
  stop: "停止",
  swipeToConfirm: "スワイプして確認",
  textCopiedToClipboard: "テキストをクリップボードにコピーしました",
  true: "正",
  tryAgain: "再試行",
  yes: "はい",

  timePart: {
    year: "年",
    year_plural: "か年",
    month: "月",
    month_plural: "か月",
    day: "日",
    day_plural: "日",
    hour: "時間",
    hours: "時間",
    minute: "分",
    minute_plural: "分",
    second: "秒",
    second_plural: "秒",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "約{{hours}}時間{{minutes}}分続く可能性があります",
    canLastTimePart: "約{{count}} {{timePart}}続く可能性があります",
    hoursAndMinutesShort: "{{hours}}時間{{minutes}}分",
    lessThanOneTimePart: "残り１{{timePart}}未満",
    timePartLeft: "残り{{count}} {{timePart}}",
  },
  warning: "警告",
  warning_other: "警告",
};
