export enum screenKeys {
  about = "about",
  home = "home",
  locationMapViewer = "locationMapViewer",
  offlineMapAreaEditor = "offlineMapAreaEditor",
  offlineMapAreaViewer = "offlineMapAreaViewer",
  offlineMaps = "offlineMaps",
  recordsList = "recordsList",
  recordsMap = "recordsMap",
  recordEditor = "recordEditor",
  recordValidationReport = "recordValidationReport",
  settings = "settings",
  settingsRemoteConnection = "settingsRemoteConnection",
  surveysListLocal = "surveysListLocal",
  surveysListRemote = "surveysListRemote",
}
