const initConnection$ = 'app/initConnection$';
const logout$ = 'app/logout$';
const SET_ACCESS_DATA = 'app/SET_ACCESS_DATA';
const CLEAN_ACCESS_DATA = 'app/CLEAN_ACCESS_DATA';
const SET_SERVER_URL = 'app/SET_SERVER_URL';
const CLEAN = 'app/CLEAN';

/*ui*/
const SET_LOADING = 'app/SET_LOADING';
const CLEAN_ERRORS = 'app/CLEAN_ERRORS';
const SET_SERVER_ERROR = 'app/SET_SERVER_ERROR';
const SET_CREDENTIALS_ERROR = 'app/SET_CREDENTIALS_ERROR';
const SET_SHOW_NAMES = 'app/SET_SHOW_NAMES';
const SET_DEV_MODE = 'app/SET_DEV_MODE';
const DISABLE_DEV_MODE = 'app/DISABLE_DEV_MODE';

/* Preferences settings */
const SET_SETTINGS_PREFERENCES_SURVEY_TAXONOMIES_DEFAULT_VISIBLE_FIELDS =
  'app/SET_SETTINGS_PREFERENCES_SURVEY_TAXONOMIES_DEFAULT_VISIBLE_FIELDS';

const SET_STYLE_BASE_MODIFIER = 'app/SET_STYLE_BASE_MODIFIER';
const SET_STYLE_FONT_BASE_MODIFIER = 'app/SET_STYLE_FONT_BASE_MODIFIER';
const SET_STYLE_COLOR_SCHEME = 'app/SET_STYLE_COLOR_SCHEME';

/* images settings */
const SET_IMAGES_COMPRESS_QUALITY = 'app/SET_IMAGES_COMPRESS_QUALITY';
const SET_IMAGES_COMPRESS_MAX_HEIGHT = 'app/SET_IMAGES_COMPRESS_MAX_HEIGHT';
const SET_IMAGES_COMPRESS_MAX_WIDTH = 'app/SET_IMAGES_COMPRESS_MAX_WIDTH';
const SET_IS_MAX_RESOLUTION = 'app/SET_IS_MAX_RESOLUTION';

export default {
  initConnection$,
  logout$,
  SET_ACCESS_DATA,
  CLEAN_ACCESS_DATA,
  SET_SERVER_URL,
  CLEAN,

  /*ui*/
  SET_LOADING,
  CLEAN_ERRORS,
  SET_SERVER_ERROR,
  SET_CREDENTIALS_ERROR,
  SET_SHOW_NAMES,
  SET_DEV_MODE,
  DISABLE_DEV_MODE,

  /* Preferences settings */
  SET_SETTINGS_PREFERENCES_SURVEY_TAXONOMIES_DEFAULT_VISIBLE_FIELDS,

  /* Style settings */
  SET_STYLE_BASE_MODIFIER,
  SET_STYLE_FONT_BASE_MODIFIER,
  SET_STYLE_COLOR_SCHEME,

  /* Images settings */
  SET_IMAGES_COMPRESS_QUALITY,
  SET_IMAGES_COMPRESS_MAX_HEIGHT,
  SET_IMAGES_COMPRESS_MAX_WIDTH,
  SET_IS_MAX_RESOLUTION,
};
