export default {
  about: "Tietoja",
  appTitle: "Arena Mobile 2",
  cancel: "Kumoa",
  clear: "Tyhjennä",
  close: "Sulje",
  confirm: "Vahvista",
  confirmClearSelectedValue: "Tyhjennä valittu tieto?",
  confirmClearSelectedValue_plural: "Tyhjennä valitut tiedot?",
  continue: "Jatka",
  createdOn: "Luotu",
  delete: "Poista",
  deleteSelectedTitle: "Poista valitut",
  details: "Tiedot",
  done: "Valmis",
  empty: "--- TYHJÄ ---",
  error: "Virhe",
  exit: "Poistu",
  export: "Vie",
  false: "Epätosi",
  filter: "Suodata",
  fromToOf: `{{from}}-{{to}} / {{of}}`,
  goBack: "Palaa takaisin",
  import: "Tuoda",
  info: "Info",
  label: "Nimiö",
  legend: "Selite",
  modifiedOn: "Muokattu",
  name: "Nimi",
  networkNotAvailable: "Verkko ei ole käytettävissä!",
  newItemWithParam: "Uusi {{item}}",
  no: "Ei",
  noItemsMatchingSearch: "Hakuehtoja vastaavia kohteita ei löydy",
  notEnoughDiskSpace:
    "Ei tarpeeksi vapaata levytilaa (tarvitaan vielä {{requiredSpace}})",
  ok: "Ok",
  path: "Polku",
  rowsPerPage: "Rivejä sivulla",
  search: "Haku",
  selectAnItem: "Valitse kohde",
  selectNewItems: "Valitse uusia kohteita",
  shareFile: "Jaa tiedosto",
  size: "Koko",
  sizeAvailable: "{{size}} käytettävissä",
  somethingWentWrong: "Jokin meni pieleen: {{error}}",
  srs: "SRS",
  status: "Tila",
  stop: "Pysäytä",
  swipeToConfirm: "Pyyhkäise vahvistaaksesi",
  textCopiedToClipboard: "Teksti kopioitu leikepöydälle",
  true: "Tosi",
  yes: "Kyllä",

  timePart: {
    year: "vuosi",
    year_plural: "vuotta",
    month: "kuukausi",
    month_plural: "kuukautta",
    day: "päivä",
    day_plural: "päivää",
    hour: "tunti",
    hours: "tuntia",
    minute: "minuutti",
    minute_plural: "minuuttia",
    second: "sekunti",
    second_plural: "sekuntia",
  },
  remainingTime: {
    canLastHoursAndMinutes: "Se voi kestää noin {{hours}} h ja {{minutes}} min",
    canLastTimePart: "Se voi kestää noin {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h ja {{minutes}} min",
    lessThanOneTimePart: "vähemmän kuin yksi {{timePart}} jäljellä",
    timePartLeft: "{{count}} {{timePart}} jäljellä",
  },
  warning: "Varoitus",
};
