export default {
  about: "Om",
  appTitle: "Arena Mobile 2",
  cancel: "Avbryt",
  clear: "Rensa",
  close: "Stäng",
  confirm: "Bekräfta",
  confirmClearSelectedValue: "Rensa valt värde?",
  confirmClearSelectedValue_plural: "Rensa valda värden?",
  continue: "Fortsätt",
  createdOn: "Skapad den",
  delete: "Ta bort",
  deleteSelectedTitle: "Ta bort valda",
  details: "Detaljer",
  done: "Klar",
  empty: "--- TOM ---",
  error: "Fel",
  exit: "Avsluta",
  export: "Exportera",
  false: "Falskt",
  filter: "Filtrera",
  fromToOf: `{{from}}-{{to}} av {{of}}`,
  goBack: "Gå tillbaka",
  import: "Importera",
  info: "Info",
  label: "Etikett",
  legend: "Förklaring",
  modifiedOn: "Ändrad den",
  name: "Namn",
  networkNotAvailable: "Nätverk inte tillgängligt!",
  newItemWithParam: "Ny {{item}}",
  no: "Nej",
  noItemsMatchingSearch: "Det finns inga objekt som matchar din sökning",
  notEnoughDiskSpace:
    "Inte tillräckligt med ledigt diskutrymme ({{requiredSpace}} mer krävs)",
  ok: "Ok",
  path: "Sökväg",
  rowsPerPage: "Rader per sida",
  search: "Sök",
  selectAnItem: "Välj ett objekt",
  selectNewItems: "Välj nya objekt",
  shareFile: "Dela fil",
  size: "Storlek",
  sizeAvailable: "{{size}} tillgängligt",
  somethingWentWrong: "Något gick fel: {{error}}",
  srs: "SRS",
  status: "Status",
  stop: "Stopp",
  swipeToConfirm: "Svep för att bekräfta",
  textCopiedToClipboard: "Text kopierad till urklipp",
  true: "Sant",
  yes: "Ja",

  timePart: {
    year: "år",
    year_plural: "år",
    month: "månad",
    month_plural: "månader",
    day: "dag",
    day_plural: "dagar",
    hour: "timme",
    hours: "timmar",
    minute: "minut",
    minute_plural: "minuter",
    second: "sekund",
    second_plural: "sekunder",
  },
  remainingTime: {
    canLastHoursAndMinutes: "Det kan ta runt {{hours}} h och {{minutes}} min",
    canLastTimePart: "Det kan ta runt {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} h och {{minutes}} min",
    lessThanOneTimePart: "mindre än en {{timePart}} kvar",
    timePartLeft: "{{count}} {{timePart}} kvar",
  },
  warning: "Varning",
};
