export default {
  about: "Tentang",
  appTitle: "Arena Mobile 2",
  cancel: "Batal",
  clear: "Bersihkan",
  close: "Tutup",
  confirm: "Konfirmasi",
  confirmClearSelectedValue: "Bersihkan nilai yang dipilih?",
  confirmClearSelectedValue_plural: "Bersihkan nilai-nilai yang dipilih?",
  continue: "Lanjutkan",
  createdOn: "Dibuat pada",
  delete: "Hapus",
  deleteSelectedTitle: "Hapus yang dipilih",
  details: "Detail",
  done: "Selesai",
  empty: "--- KOSONG ---",
  error: "Kesalahan",
  exit: "Keluar",
  export: "Ekspor",
  false: "Salah",
  filter: "Saring",
  fromToOf: `{{from}}-{{to}} dari {{of}}`,
  goBack: "Kembali",
  info: "Info",
  label: "Label",
  legend: "Legenda",
  modifiedOn: "Diubah pada",
  name: "Nama",
  networkNotAvailable: "Jaringan tidak tersedia!",
  newItemWithParam: "{{item}} Baru",
  no: "Tidak",
  noItemsMatchingSearch: "Tidak ada item yang sesuai dengan pencarian Anda",
  notEnoughDiskSpace:
    "Tidak cukup ruang disk (diperlukan {{requiredSpace}} lagi)",
  ok: "Ok",
  path: "Path",
  rowsPerPage: "Baris per halaman",
  search: "Cari",
  selectAnItem: "Pilih item",
  selectNewItems: "Pilih item baru",
  shareFile: "Bagikan file",
  size: "Ukuran",
  sizeAvailable: "{{size}} tersedia",
  somethingWentWrong: "Terjadi kesalahan: {{error}}",
  srs: "SRS",
  status: "Status",
  stop: "Berhenti",
  swipeToConfirm: "Geser untuk konfirmasi",
  textCopiedToClipboard: "Teks disalin ke clipboard",
  true: "Benar",
  yes: "Ya",

  timePart: {
    year: "tahun",
    year_plural: "tahun",
    month: "bulan",
    month_plural: "bulan",
    day: "hari",
    day_plural: "hari",
    hour: "jam",
    hours: "jam",
    minute: "menit",
    minute_plural: "menit",
    second: "detik",
    second_plural: "detik",
  },
  remainingTime: {
    canLastHoursAndMinutes:
      "Dapat bertahan sekitar {{hours}} jam dan {{minutes}} menit",
    canLastTimePart: "Dapat bertahan sekitar {{count}} {{timePart}}",
    hoursAndMinutesShort: "{{hours}} jam dan {{minutes}} menit",
    lessThanOneTimePart: "kurang dari satu {{timePart}} tersisa",
    timePartLeft: "{{count}} {{timePart}} tersisa",
  },
  warning: "Peringatan",
};
