export default {
  clearCredentials: "Hapus kredensial",
  clearCredentialsConfirmMessage: "Hapus kredensial pengguna?",
  email: "Email",
  errorConnectingWithServer: "Kesalahan saat terhubung dengan server",
  forgotPassword: "Lupa kata sandi?",
  login: "Masuk",
  loginUsingQrCode: "Masuk menggunakan kode QR",
  logout: "Keluar",
  logoutConfirmMessage: "Keluar dan hapus kredensial pengguna?",
  password: "Kata sandi",
  qrCodeNotValid: "Kode QR tidak valid",
  requestAccess: "Baru di Arena? Minta akses",
  scanQrCode: "Pindai kode QR",
  serverUrl: "URL Server",
  serverUrlNotValid: "URL Server tidak valid",
  serverUrlType: {
    default: "Default",
    custom: "Kustom",
  },
  testUrl: "Uji URL",
  title: "Koneksi ke server",
};
