name: E2E Maestro Android

on: [pull_request]

jobs:
  maestro-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: "https://npm.pkg.github.com"
          scope: "@openforis"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Maestro CLI
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build app and run Maestro
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ARENA_SERVER_URL: ${{secrets.ARENA_SERVER_URL}}
          ARENA_SERVER_USERNAME: ${{secrets.ARENA_SERVER_USERNAME}}
          ARENA_SERVER_PASSWORD: ${{secrets.ARENA_SERVER_PASSWORD}}
        with:
          api-level: 35
          arch: x86_64
          profile: pixel_7
          script: |
            npx expo run:android --variant debug
            yarn e2e:maestro:android e2e/maestro/ -e ARENA_SERVER_URL=$ARENA_SERVER_URL -e ARENA_SERVER_USERNAME=$ARENA_SERVER_USERNAME -e ARENA_SERVER_PASSWORD=$ARENA_SERVER_PASSWORD
