name: E2E Maestro Android

on: [pull_request]

jobs:
  e2e-tests-maestro-android:
    runs-on: macos-latest
    env:
      NPM_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: "https://npm.pkg.github.com"
          scope: "@openforis"

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Maestro CLI
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Build the APK FIRST (No emulator yet)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - name: Build Android APK
        run: |
          npx expo prebuild --platform android
          cd android && ./gradlew assembleDebug -Dorg.gradle.daemon=false

      # Now start the Emulator and run Maestro
      - name: Run Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ARENA_SERVER_URL: ${{secrets.ARENA_SERVER_URL}}
          ARENA_SERVER_USERNAME: ${{secrets.ARENA_SERVER_USERNAME}}
          ARENA_SERVER_PASSWORD: ${{secrets.ARENA_SERVER_PASSWORD}}
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_7
          disable-animations: true
          # Increase timeout because software-rendering is slow
          emulator-boot-timeout: 900
          script: |
            echo "Waiting for emulator to settle..."
            adb wait-for-device

            echo "Waiting for Package Manager..."
            until adb shell pm list packages >/dev/null 2>&1; do sleep 5; done

            echo "Installing APK..."
            # Use -r to replace if exists, -t for test packages (Expo debug builds need this)
            adb install -r -t android/app/build/outputs/apk/debug/app-debug.apk

            echo "Running Maestro..."
            # Give the OS 10 seconds to 'breathe' after installation
            sleep 10
            yarn e2e:maestro:android -e ARENA_SERVER_URL=$ARENA_SERVER_URL -e ARENA_SERVER_USERNAME=$ARENA_SERVER_USERNAME -e ARENA_SERVER_PASSWORD=$ARENA_SERVER_PASSWORD
