name: E2E Maestro Android

on: [pull_request]

jobs:
  e2e-tests-maestro-android:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: yarn
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: "https://npm.pkg.github.com"
          scope: "@openforis"

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Maestro CLI
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build app and run Maestro
        uses: reactivecircus/android-emulator-runner@v2
        env:
          ARENA_SERVER_URL: ${{secrets.ARENA_SERVER_URL}}
          ARENA_SERVER_USERNAME: ${{secrets.ARENA_SERVER_USERNAME}}
          ARENA_SERVER_PASSWORD: ${{secrets.ARENA_SERVER_PASSWORD}}
        with:
          api-level: 35
          arch: x86_64
          profile: pixel_7
          script: |
            echo "Starting Prebuild..."
            npx expo prebuild --platform android

            echo "Building APK..."
            cd android && ./gradlew assembleDebug \
              -Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxMetaspaceSize=512m" \
              -Dorg.gradle.daemon=false \
              -Dorg.gradle.parallel=false            
            cd ..

            echo "Installing APK..."
            adb install android/app/build/outputs/apk/debug/app-debug.apk

            echo "Running Maestro..."
            yarn e2e:maestro:android -e ARENA_SERVER_URL=$ARENA_SERVER_URL -e ARENA_SERVER_USERNAME=$ARENA_SERVER_USERNAME -e ARENA_SERVER_PASSWORD=$ARENA_SERVER_PASSWORD
