name: Deploy to Android

on:
  push:
    branches:
      - 'master'

jobs:
  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.0'
          always-auth: true
          auth-token: ${{secrets.ACCESS_TOKEN}}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@openforis'
        env:
          ACCESS_TOKEN: $${{secrets.ACCESS_TOKEN}}
      - name: Install
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
        run: bundle exec rake
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'arena-release-key.keystore'
          fileDir: './android'
          encodedString: ${{ secrets.KEYSTORE }}
      - name: Decode Play json
        id: decode_play_json
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: '4428354186-c469bd85b036.json'
          fileDir: './android'
          encodedString: ${{ secrets.GOOGLE_PLAY_JSON }}
      - name: Install Fastlane
        run: cd android && bundle install && cd ..
      - name: Execute Fastlane command
        run: cd android && fastlane android beta
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          ANDROID_KEYSTORE_PASSWORD: ${{secrets.ANDROID_KEYSTORE_PASSWORD}}
          PACKAGE_NAME: 'org.openforis.collect.arena'
